### ISSUE TITLE
Support for Stockalike Station Parts Airlocks

### ISSUE THREAD

**Issue by fraz86** [timmersuk/Timmers_KSP#4]
@PART[crewtube-airlock-125]:NEEDS[KeepFit]:AFTER[KeepFit]
{
    MODULE
    {
        name = KeepFitPartModule
    strActivityLevel = CRAMPED
    }
}
@PART[crewtube-airlock-25]:NEEDS[KeepFit]:AFTER[KeepFit]
{
    MODULE
    {
        name = KeepFitPartModule
    strActivityLevel = CRAMPED
    }
}

**Comment by timmersuk** [comment]
Added in 0.10.4.3 for 1.1 prelease - many apologies for not acknowledging you in the commit log - I'd forgotten who added them (or even if it was my own addition!)
